In [3]:
import tensorflow as tf

In [4]:
# 占位符的使用
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
add = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(add,feed_dict={data1:6,data2:2}))

8.0


In [9]:
# 一个一行两列的矩阵[[6,6]],两行两列[[1,1],[2,2]]
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                     [3,4],
                     [5,6]])
# 查看矩阵维度
print(data4.shape)
with tf.Session() as sess:
    # 打印整体
    print(sess.run(data4))
    # 打印第0行
    print(sess.run(data4[0]))
    # 打印第0列
    print(sess.run(data4[:,0]))
    # 打印第0行第0列
    print(sess.run(data4[0,0]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1


In [12]:
# 矩阵乘法
matMul = tf.matmul(data1,data2)
# 矩阵加法
matAdd = tf.add(data1,data3)
# 一般乘法，即基于广播机制的乘法
matMul2 = tf.multiply(data1,data2)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))
    print(sess.run(matMul2))
    # session一次运行多个结果
    print(sess.run([matMul,matAdd,matMul2]))

[[24]]
[[9 9]]
[[12 12]
 [12 12]]
[array([[24]]), array([[9, 9]]), array([[12, 12],
       [12, 12]])]


In [16]:
# 定义2 * 3的空矩阵的几种方式
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])
# 定义全1矩阵
mat2 = tf.ones([3,2])
# 自定义矩阵并填充相应的值
mat3 = tf.fill([3,2],15)
with tf.Session() as sess:
    print(sess.run(mat0))   
    print(sess.run(mat1))      
    print(sess.run(mat2))     
    print(sess.run(mat3))     

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15]
 [15 15]
 [15 15]]


In [21]:
mat1 = tf.constant([[1],[2],[3]])
# 根据mat1的维度构造全零矩阵
mat2 = tf.zeros_like(mat1)
# 把构造一维数组，数据从0.0到2.0，一共十等分。
mat3 = tf.linspace(0.0,2.0,11)
# 产生一个2*3维度的随机数矩阵，数据范围为-1~2
mat4 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat1))   
    print(sess.run(mat2))  
    print(sess.run(mat3))  
    print(sess.run(mat4))  

[[1]
 [2]
 [3]]
[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[ 1.8353117  -0.4672382  -0.25301373]
 [-0.69803476  0.9580215  -0.8979262 ]]
