In [1]:
import numpy as np

In [12]:
# 构造矩阵
data1 = np.array([1,2,3,4,5])
print(data1)
data2 = np.array([[1,2],[3,4]])
print(data2)
# 修改矩阵第1行和第0列
data2[1,0] = 5
print(data2)
# 矩阵基本运算
data3 = np.ones([2,3])
# 与常数进行基本运算(所有元素与常数做相应的运算)
print(data3*2)
print(data3/2)
print(data3+2)
print(data3-2)
# 与矩阵进行基本运算(对应元素分别做计算)
data4 = np.array([[1,2,3],[4,5,6]])
print(data3+data4)
print(data3-data4)
print(data3*data4)
print(data3/data4)

[1 2 3 4 5]
[[1 2]
 [3 4]]
[[1 2]
 [5 4]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-1. -1. -1.]
 [-1. -1. -1.]]
[[2. 3. 4.]
 [5. 6. 7.]]
[[ 0. -1. -2.]
 [-3. -4. -5.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [5]:
# 矩阵维度
print(data1.shape,data2.shape)

(5,) (2, 2)


In [7]:
# 空矩阵
print(np.zeros([2,3]))
# 单位矩阵
print(np.ones([2,3]))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
